---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1.0.0
      - uses: codespell-project/actions-codespell@v2.0
        with:
          check_hidden: false
          ignore_words_list: hass
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: **/requirements_dev.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Static typing with mypy
        run: |
          mypy --install-types --non-interactive --no-warn-unused-ignores custom_components
