---
name: Lint

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3.5
      - uses: codespell-project/actions-codespell@v2.1
        with:
          check_hidden: false
          ignore_words_list: hass
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "requirements_dev.txt"
          activate-environment: true
      - name: Install dependencies
        run: |
          uv pip install -r requirements_dev.txt --prerelease=allow

      - name: Static typing with mypy
        run: |
          mypy --install-types --non-interactive --no-warn-unused-ignores custom_components
